### ISSUE TITLE
do you have some benchmark result in kitti odometry lidar dataset ?

### ISSUE THREAD

**Issue by weidezhang** [kissb2/PyICP-SLAM#1]

**Comment by gisbi-kim** [comment]
I do not have the evaluation results on this source yet because this repository's aim is not competing for the result, but more for a tutorial. 

But I think 
you can easily extract the predicted trajectory (by just running the main py code) 
and save them to your text file, 
and submit the result to the KITTI website (then you can immediately get results) 
or use the RPG trajectory evaluator (https://github.com/uzh-rpg/rpg_trajectory_evaluation) for the benchmark result.

**Comment by weidezhang** [comment]
got it. thx
